### ISSUE TITLE
Volo

### ISSUE THREAD

**Issue by FabioZTessitore** [luca998/volo#1]
Utilizzando il linguaggio Python si scriva un programma volo.py

```python
# determinare la durata massima di volo conoscendo
# la quantita' di carburante ed il consumo orario

carburante = 1460. # galloni USA
consumo_h = 320. # galloni USA / h
```

**Comment by luca998** [comment]
ho caricato la mia versione

**Comment by FabioZTessitore** [comment]
va benino

1) hai fatto una furbata. Nel testo dell'esercizio i valori erano float (c'è il punto finale)
2) i nomi delle variabili sono incomprensibili (nel senso che da una prima lettura non si capisce chi siano i valori contenuti)

**Comment by luca998** [comment]
ora lo modifico

**Comment by FabioZTessitore** [comment]
ok, promosso a gialla haha
